### ISSUE TITLE
Unlimited number of message keys stored

### ISSUE THREAD

**Issue by joebandenburg** [WhisperSystems/libaxolotl-android#3]
Correct my if I'm wrong, but it looks like there is no limit on the number of message keys that can be stored for a given chain key. In contrast, chain keys have a limit of 5.

An attacker could send messages to a client with a counter that increments by 2000 each time. Each time the client receives one of these messages, it is forced to compute and store 2000 more message keys. To make matters worse, the client must do this before it has checked the message is authentic, so an attacker doesn't even have to be able to produce authentic messages. I'm not sure how the UI deals with `InvalidMessageExceptions`, but if it silently ignores them then the user will not even be aware this is happening.

A quick back-of-the-envelope calculation gives:
```
80 bytes per message key * 2000 keys * 10000 messages = 1.49GiB of storage used
```

It wouldn't take long for an attacker to fill a user's storage.

Have you considered this issue?

**Comment by moxie0** [comment]
Nothing is stored if the MAC isn't correct. We'll slowly reduce the limit over time.
